const IMAGES = {
    am_pcloudy: require("./am_pcloudy.png"),
    am_pcloudyr: require("./am_pcloudyr.png"),
    am_showers: require("./am_showers.png"),
    am_tstorm: require("./am_tstorm.png"),
    clear: require("./clear.png"),
    cloudy: require("./cloudy.png"),
    fog: require("./fog.png"),
    pcloudy: require("./pcloudy.png"),
    pcloudyr: require("./pcloudyr.png"),
    rain: require("./rain.png"),
    sunny: require("./sunny.png"),
    tstorm: require("./tstorm.png"),
    wind: require("./wind.png"),
    pm_pcloudy: require("./pm_pcloudy.png"),
    pcloudyt: require("./pcloudyt.png"),
    fair: require("./fair.png"),
    sunrise: require("./sunrise.png"),
    sunset: require("./sunset.png"),
    happynight: require("./happynight.png"),
    halfmoon: require("./half-moon.png"),
    snorlax: require("./bigsnorlax.png"),
    mcloudyt: require("./mcloudyt.png"),
    mcloudy: require("./mcloudy.png"),
    mcloudyr: require("./mcloudyr.png"),
};

export default IMAGES;
